# Generated by Django 4.2 on 2024-08-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('genre', models.CharField(choices=[('Heavy Metal', 'Heavy Metal'), ('Indie', 'Indie'), ('Metal', 'Metal'), ('Reggaeton', 'Reggaeton'), ('Blues', 'Blues'), ('Pop', 'Pop'), ('Grunge', 'Grunge'), ('Reagge', 'Reagge'), ('Alterantivo', 'Alternativo'), ('Rock', 'Rock')], max_length=45)),
                ('year', models.IntegerField()),
                ('picture', models.ImageField(upload_to='discos_images')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist')),
            ],
        ),
    ]
