# Generated by Django 4.2 on 2024-08-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discos',
            name='genre',
            field=models.CharField(choices=[('Grunge', 'Grunge'), ('Rock', 'Rock'), ('Alterantivo', 'Alternativo'), ('Indie', 'Indie'), ('Pop', 'Pop'), ('Blues', 'Blues'), ('Reagge', 'Reagge'), ('Heavy Metal', 'Heavy Metal'), ('Metal', 'Metal'), ('Reggaeton', 'Reggaeton')], max_length=45),
        ),
    ]
