# Generated by Django 4.2 on 2024-08-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_discos_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discos',
            name='genre',
            field=models.CharField(choices=[('Blues', 'Blues'), ('Heavy Metal', 'Heavy Metal'), ('Metal', 'Metal'), ('Grunge', 'Grunge'), ('Reagge', 'Reagge'), ('Reggaeton', 'Reggaeton'), ('Indie', 'Indie'), ('Rock', 'Rock'), ('Pop', 'Pop'), ('Alterantivo', 'Alternativo')], max_length=45),
        ),
    ]
