# Generated by Django 4.2 on 2024-08-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0003_alter_discos_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discos',
            name='genre',
            field=models.CharField(choices=[('Heavy Metal', 'Heavy Metal'), ('Blues', 'Blues'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Grunge', 'Grunge'), ('Reggaeton', 'Reggaeton'), ('Alterantivo', 'Alternativo'), ('Reagge', 'Reagge'), ('Metal', 'Metal'), ('Indie', 'Indie')], max_length=45),
        ),
    ]
