# Generated by Django 4.2 on 2024-08-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0004_alter_discos_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discos',
            name='genre',
            field=models.CharField(choices=[('Grunge', 'Grunge'), ('Reagge', 'Reagge'), ('Pop', 'Pop'), ('Blues', 'Blues'), ('Reggaeton', 'Reggaeton'), ('Heavy Metal', 'Heavy Metal'), ('Indie', 'Indie'), ('Alterantivo', 'Alternativo'), ('Metal', 'Metal'), ('Rock', 'Rock')], max_length=45),
        ),
    ]
