# Generated by Django 4.2 on 2024-08-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0005_alter_discos_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discos',
            name='genre',
            field=models.CharField(choices=[('Indie', 'Indie'), ('Metal', 'Metal'), ('Blues', 'Blues'), ('Reggaeton', 'Reggaeton'), ('Rock', 'Rock'), ('Pop', 'Pop'), ('Grunge', 'Grunge'), ('Heavy Metal', 'Heavy Metal'), ('Alterantivo', 'Alternativo'), ('Reagge', 'Reagge')], max_length=45),
        ),
    ]
